# Numpy

- NumPy is a general-purpose array-processing package.
- Numpy was created to work with multidmensional arrays.
- It is the fundamental package for scientific computing with Python.
- It is open-source library.

# Why Use NumPy?
- In Python we have lists that serve the purpose of arrays, but they are slow to process.

- NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

- The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.

- Arrays are very frequently used in data science, where speed and resources are very important.

In [2]:
#Importing necessary library
import numpy as np

In [3]:
#Array Creation

x = np.array(10)
type(x)

numpy.ndarray

In [ ]:
x = np.array([10,12,16,18])

In [ ]:
x

In [ ]:
x.ndim

In [ ]:
#Zero dimensional array

In [ ]:
z = np.array(10)
z.ndim

In [ ]:
#One dimensional array

In [ ]:
o = np.array([10])
o.ndim

In [ ]:
#Two dimensional array

In [ ]:
t = np.array([[1,2,3],[4,5,6]])
t.ndim

In [ ]:
#Three dimensional array

In [ ]:
a = np.array([[[1,2,3,4,5]]])
a.ndim

In [ ]:
#Change the data type of the array elements.

In [ ]:
a = np.array([10,20,30,40,50], dtype = float)
a

In [ ]:
a = np.array(['10','20','30'])
a

# Other ways of creating an array
1. arange
2. linspace
3. zeros
4. ones
5. random

In [5]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
a = np.linspace(1,10,20,retstep=True)
a


(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [11]:
z = np.zeros([2,3])
z

array([[0., 0., 0.],
       [0., 0., 0.]])

In [12]:
o = np.ones([5,5])
o

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
x = np.random.rand(10,5)
x

array([[0.03106292, 0.99762969, 0.37794423, 0.43750576, 0.68569168],
       [0.7798882 , 0.27691269, 0.18762275, 0.21876483, 0.61319989],
       [0.14418044, 0.55336962, 0.1419727 , 0.08027219, 0.35816165],
       [0.73915847, 0.43601058, 0.82519359, 0.57086301, 0.68479251],
       [0.69241191, 0.98021212, 0.0610995 , 0.90082403, 0.2314189 ],
       [0.46176159, 0.66717398, 0.29368878, 0.99396422, 0.08263853],
       [0.18109792, 0.24089625, 0.62731664, 0.9839956 , 0.86873401],
       [0.43354619, 0.40635333, 0.42017061, 0.08389833, 0.85531764],
       [0.79812789, 0.56494188, 0.64349643, 0.10538615, 0.88084852],
       [0.84406497, 0.73688528, 0.75080103, 0.32861422, 0.77392515]])

In [16]:
np.random.randn(10,2)

array([[-0.84065315, -1.36127254],
       [-0.19180758,  0.67050047],
       [ 0.39386664, -2.02319091],
       [ 2.86310557,  2.09028193],
       [-0.19586507, -0.89220153],
       [ 0.29874826, -1.02044807],
       [ 2.39855436, -1.86520596],
       [-0.75832098, -0.22323198],
       [ 0.06484539, -0.25502275],
       [-0.2597636 ,  0.05796659]])

# Slicing and Indexing of arrays

In [17]:
x = np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
x[0,0]

1

In [21]:
x[0,0:2]

array([1, 2])

In [22]:
x[1,1:]

array([5, 6])

In [23]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
x[[0,1],[0,2]]

array([1, 6])

In [25]:
x[[0,1],[2,2]]

array([3, 6])

In [26]:
x[:,2]

array([3, 6])

# Reshaping the arrays 

In [28]:
a = np.random.rand(10,2)
a

array([[0.89625361, 0.33292576],
       [0.02684457, 0.79981644],
       [0.80849361, 0.89995029],
       [0.4414729 , 0.84058414],
       [0.00813649, 0.57704649],
       [0.96614402, 0.14167419],
       [0.98472201, 0.54393   ],
       [0.51427838, 0.5981843 ],
       [0.81013144, 0.62304524],
       [0.29169498, 0.21802639]])

In [29]:
a.reshape(2,10)

array([[0.89625361, 0.33292576, 0.02684457, 0.79981644, 0.80849361,
        0.89995029, 0.4414729 , 0.84058414, 0.00813649, 0.57704649],
       [0.96614402, 0.14167419, 0.98472201, 0.54393   , 0.51427838,
        0.5981843 , 0.81013144, 0.62304524, 0.29169498, 0.21802639]])

In [30]:
a.reshape(5,4)

array([[0.89625361, 0.33292576, 0.02684457, 0.79981644],
       [0.80849361, 0.89995029, 0.4414729 , 0.84058414],
       [0.00813649, 0.57704649, 0.96614402, 0.14167419],
       [0.98472201, 0.54393   , 0.51427838, 0.5981843 ],
       [0.81013144, 0.62304524, 0.29169498, 0.21802639]])

In [31]:
a.reshape(10,5)

ValueError: cannot reshape array of size 20 into shape (10,5)

In [32]:
a.reshape(2,-1)

array([[0.89625361, 0.33292576, 0.02684457, 0.79981644, 0.80849361,
        0.89995029, 0.4414729 , 0.84058414, 0.00813649, 0.57704649],
       [0.96614402, 0.14167419, 0.98472201, 0.54393   , 0.51427838,
        0.5981843 , 0.81013144, 0.62304524, 0.29169498, 0.21802639]])

In [33]:
a.reshape(-1,5)

array([[0.89625361, 0.33292576, 0.02684457, 0.79981644, 0.80849361],
       [0.89995029, 0.4414729 , 0.84058414, 0.00813649, 0.57704649],
       [0.96614402, 0.14167419, 0.98472201, 0.54393   , 0.51427838],
       [0.5981843 , 0.81013144, 0.62304524, 0.29169498, 0.21802639]])

In [34]:
a.reshape(-1,-1)

ValueError: can only specify one unknown dimension

# Aggregate Functions

- The Python numpy aggregate functions are sum, min, max, mean, average, product, median, standard deviation, variance,  percentile, and corrcoef.

In [35]:
a

array([[0.89625361, 0.33292576],
       [0.02684457, 0.79981644],
       [0.80849361, 0.89995029],
       [0.4414729 , 0.84058414],
       [0.00813649, 0.57704649],
       [0.96614402, 0.14167419],
       [0.98472201, 0.54393   ],
       [0.51427838, 0.5981843 ],
       [0.81013144, 0.62304524],
       [0.29169498, 0.21802639]])

In [36]:
a.min()

0.008136493668559619

In [37]:
a.max()

0.9847220141173451

In [38]:
a.mean()

0.5661677622645163

In [39]:
a.std()

0.3049745318819085

In [40]:
a.var()

0.09300946509658922

# Stacking 
- Stacking is used to join 2 different arrays.
- Vertical stacking
- Horizontal stacking

In [41]:
a = np.array([1,2,3])
b = np.array([4,5,6])

In [42]:
np.vstack([a,b])

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
np.hstack([a,b])

array([1, 2, 3, 4, 5, 6])